"""Chunk repository protocol."""

from typing import Protocol

from atenex_nova.domain.entities.chunk import Chunk


class ChunkRepository(Protocol):
    async def create(self, chunk: Chunk) -> None: ...
    async def create_many(self, chunks: list[Chunk]) -> None: ...
    async def update(self, chunk: Chunk) -> None: ...
    async def get_by_document(self, document_id: str) -> list[Chunk]: ...
    async def delete_by_document(self, document_id: str) -> bool: ...
