"""DocumentNode repository protocol."""
from typing import Protocol

from atenex_nova.domain.entities.document_node import DocumentNode


class DocumentNodeRepository(Protocol):
    async def create(self, node: DocumentNode) -> None: ...
    async def create_many(self, nodes: list[DocumentNode]) -> None: ...
    async def get_by_document(self, document_id: str) -> list[DocumentNode]: ...
    async def delete_by_document(self, document_id: str) -> bool: ...
