"""Proposition repository protocol."""

from typing import Protocol

from atenex_nova.domain.entities.proposition import Proposition


class PropositionRepository(Protocol):
    async def create_many(self, propositions: list[Proposition]) -> list[Proposition]: ...
    async def list_by_document(self, document_id: str) -> list[Proposition]: ...
    async def list_by_collection(self, collection_id: str) -> list[Proposition]: ...
    async def delete_by_document(self, document_id: str) -> bool: ...