"""Summary repository protocol."""

from typing import Protocol

from atenex_nova.domain.entities.summary_node import SummaryNode


class SummaryRepository(Protocol):
    async def create_many(self, summaries: list[SummaryNode]) -> list[SummaryNode]: ...
    async def list_by_scope(self, scope_type: str, scope_id: str) -> list[SummaryNode]: ...
    async def list_by_collection(self, collection_id: str) -> list[SummaryNode]: ...
    async def delete_by_scope(self, scope_type: str, scope_id: str) -> bool: ...